name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bradly0cjw
          template: classic
          base: header, activity, community, repositories, metadata
          repositories_forks: yes
          config_timezone: Asia/Taipei
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          plugin_activity: yes
          plugin_activity_timestamps: yes
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          plugin_traffic: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: chartlist
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_languages_limit: 20
          plugin_habits_languages_threshold: 0%
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: "${{ secrets.SPID_TOKEN }},${{ secrets.SPSE_TOKEN }},${{ secrets.SPRE_TOKEN }}"
          plugin_music_played_at: yes
          
